{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\nTest_BlogAllure.py:10: AssertionError"}, "description": "this test fails", "start": 1623156736955, "stop": 1623156736955, "uuid": "1b53acda-d119-4d3f-8a26-07db8f148ad2", "historyId": "3e7793b3dae34db39a4a9b4f96ca4037", "testCaseId": "3252bef871ecb8c68e132be868df6e36", "fullName": "Test_BlogAllure#test_failure", "labels": [{"name": "suite", "value": "Test_BlogAllure"}, {"name": "host", "value": "MININT-I84MTFS"}, {"name": "thread", "value": "25880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_BlogAllure"}]}